services:
  postgres:
    image: postgres:17
    container_name: local-huli
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: local-huli
      POSTGRES_USER: huli
      POSTGRES_PASSWORD: huli
    tmpfs:
      - /var/lib/postgresql/data
