services:
  postgres:
    image: postgres:17
    container_name: local-ehr-context-engineering-demo
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: local-ehr-context-engineering-demo
      POSTGRES_USER: local-ehr-context-engineering-user
      POSTGRES_PASSWORD: local-ehr-context-engineering-password
    tmpfs:
      - /var/lib/postgresql/data
